name: jest-ci

on: push

jobs:
  test-front:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Goto client and run tests
        run: cd client && npm i && npm test
  docker:
    needs: test-front # lance le job test-front avant de lancer le job docker
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2 # permet de faire tourner des images arm sur des machines x86
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 # va chercher docker buildx et le met en place
      - name: Login to Docker Hub
        uses: docker/login-action@v2 # va chercher les credentials pour se connecter à dockerhub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4 # va chercher l'image docker et la push sur dockerhub
        with:
          push: true
          context: "{{defaultContext}}:client"
          tags: msxromain/quete1902:latest
